FROM rustlang/rust@sha256:5920bd2df9e9b54ad743364c8c1e42532e6fd8ce232d8457f43afc9a516463a7

RUN apt-get update \
    && DEBIAN_FRONTEND=noninteractive apt-get install -y --no-install-recommends \
       valgrind=1:3.19.0-1 \
    && rm -rf /var/lib/apt/lists/* \
    && cargo install cargo-fuzz --version 0.13.2 --locked

WORKDIR /work

CMD ["sh", "scripts/run-assurance-in-container.sh"]
